CREATE DATABASE IF NOT EXISTS nyi;
USE nyi;

CREATE TABLE IF NOT EXISTS nyi (
	id INT AUTO_INCREMENT PRIMARY KEY,
	token varchar(255) NOT NULL
);

CREATE USER IF NOT EXISTS 'nyi'@'%' IDENTIFIED BY 'nyi';
GRANT ALL PRIVILEGES ON nyi.* to 'nyi'@'%';
FLUSH PRIVILEGES;
